# Generated by Django 3.2.18 on 2023-03-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digigallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
