# Generated by Django 3.2.18 on 2023-03-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digigallery', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
